name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-go@v4

    - name: Test
      run: go test -v ./...

  e2e-test:
    name: E2E test
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-go@v4

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Resolve dependencies
      working-directory: e2e
      run: npm install

    - name: Run E2E test
      working-directory: e2e
      run: make test
